# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(1547, 574)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    color:#fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color:#040f13;\n"
"}\n"
"#side_menu{\n"
"    background-color:#071e26;\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    padding:10px;\n"
"    background-color:#071e26;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    padding:10px;\n"
"    background-color:#12394a;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"\n"
"#main_body{\n"
"    background-color:#071e26;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"#texto{\n"
"    background-color:#071e26;\n"
"    border-radius:10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mapa = QtWidgets.QLabel(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapa.sizePolicy().hasHeightForWidth())
        self.mapa.setSizePolicy(sizePolicy)
        self.mapa.setMaximumSize(QtCore.QSize(1200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.mapa.setFont(font)
        self.mapa.setAlignment(QtCore.Qt.AlignCenter)
        self.mapa.setObjectName("mapa")
        self.horizontalLayout_2.addWidget(self.mapa)
        self.verticalLayout.addWidget(self.header)
        self.encabezado = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encabezado.sizePolicy().hasHeightForWidth())
        self.encabezado.setSizePolicy(sizePolicy)
        self.encabezado.setMinimumSize(QtCore.QSize(0, 0))
        self.encabezado.setMaximumSize(QtCore.QSize(1200, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setKerning(True)
        self.encabezado.setFont(font)
        self.encabezado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.encabezado.setAlignment(QtCore.Qt.AlignCenter)
        self.encabezado.setObjectName("encabezado")
        self.verticalLayout.addWidget(self.encabezado)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.side_menu = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_menu.sizePolicy().hasHeightForWidth())
        self.side_menu.setSizePolicy(sizePolicy)
        self.side_menu.setMaximumSize(QtCore.QSize(1250, 425))
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.etiqueta = QtWidgets.QLabel(self.side_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etiqueta.sizePolicy().hasHeightForWidth())
        self.etiqueta.setSizePolicy(sizePolicy)
        self.etiqueta.setText("")
        self.etiqueta.setPixmap(QtGui.QPixmap("image/Adyacencia.png"))
        self.etiqueta.setScaledContents(True)
        self.etiqueta.setObjectName("etiqueta")
        self.verticalLayout_3.addWidget(self.etiqueta)
        self.verticalLayout_2.addWidget(self.side_menu)
        self.volver = QtWidgets.QPushButton(self.frame)
        self.volver.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.volver.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Imagen5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.volver.setIcon(icon)
        self.volver.setObjectName("volver")
        self.verticalLayout_2.addWidget(self.volver)
        self.verticalLayout.addWidget(self.frame)
        SecondWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "MainWindow"))
        self.mapa.setText(_translate("SecondWindow", "MAPA - RISARALDA"))
        self.encabezado.setText(_translate("SecondWindow", "Tabla de Adyacencia de los municipios del departamento de Risaralda"))
        self.volver.setText(_translate("SecondWindow", "Volver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
